version: "3"
services:
   adguardhome:
     image: adguard/adguardhome:latest
     container_name: adguardhome
     restart: always
     ports:
       - 53:53/tcp #zwyklyDNS
       - 53:53/udp #zwyklyDNS
       - 853:853/tcp  #DNSoverTLS
       - 3000:3000/tcp #adminpanel
     volumes:
       - /adguardhome/work:/opt/adguardhome/work
       - /adguardhome/conf:/opt/adguardhome/conf
