version: "3"
services:
  npm: 
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 80:80 #Polaczenia_przychodzace_HTTP
      - 443:443 #Polaczenia_przychodzace_HTTPS
      - 81:81 #Panel_sterowania
    volumes:
      - /npm/data:/data
      - /npm/letsencrypt:/etc/letsencrypt
